ci:
  autoupdate_commit_msg: 'build(deps): pre-commit autoupdate'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.3
    hooks:
    - id: check-github-workflows
  - repo: https://github.com/coatl-dev/hadolint-coatl
    rev: 2.13.1
    hooks:
      - id: hadolint
