name: publish

on:
  push:
    branches:
      - 'coatl'
  schedule:
    - cron: '0 20 14,28 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [jython, python]
        platform: [amd64, arm64]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha,scope=${{ matrix.variant }}-${{ matrix.platform }}
          cache-to: type=gha,scope=${{ matrix.variant }}-${{ matrix.platform }},mode=max
          file: ${{ matrix.variant }}/Dockerfile
          platforms: linux/${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/ignition-devs/devcontainer-base:${{ matrix.variant }}
