name: publish

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish.yml
      - jython/**
      - python/**
      - requirements/**
  workflow_dispatch:

jobs:
  publish:
    uses: coatl-dev/workflows/.github/workflows/docker-build-push-multi-platform.yml@3b10e4c46730151093c7ccbc52fd689a48b94726 # v7.0.16
    strategy:
      matrix:
        variant: [jython, python]
    with:
      registry-image: quay.io/ignition-devs/devcontainer-base
      metadata-tags: |
        ${{ matrix.variant }}
      registry-address: quay.io
      registry-username: ${{ vars.QUAY_USERNAME }}
      build-file: ${{ matrix.variant }}/Dockerfile
      build-digest-key: ${{ matrix.variant }}
    secrets:
      registry-password: ${{ secrets.QUAY_ROBOT_TOKEN }}
