name: publish

on:
  push:
    branches:
      - 'main'
    paths:
      - 'jython/**'
      - 'python/**'
      - 'requirements/**'
  workflow_dispatch:

jobs:
  publish:
    uses: coatl-dev/workflows/.github/workflows/docker-build-push-multi-platform.yml@v4
    strategy:
      matrix:
        variant: [jython, python]
    with:
      registry-image: quay.io/ignition-devs/devcontainer-base
      metadata-tags: |
        ${{ matrix.variant }}
      registry-address: quay.io
      registry-username: ${{ vars.QUAY_USERNAME }}
      build-file: ${{ matrix.variant }}/Dockerfile
      build-digest-key: ${{ matrix.variant }}
    secrets:
      registry-password: ${{ secrets.QUAY_ROBOT_TOKEN }}
